-- Knowledge Sharing Site Schema for Oracle Database 19c+
-- 목적:
-- 1) 지식공유 서비스의 핵심 도메인(회원/토픽/게시글/댓글/태그/반응/북마크/첨부파일) 지원
-- 2) 성능(조회 인덱스)과 무결성(제약조건) 기본 반영
-- 3) 운영 확장을 위한 감사/소프트삭제 컬럼 제공

-------------------------------------------------------------------------------
-- USERS & AUTHORIZATION
-------------------------------------------------------------------------------
CREATE TABLE users (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  email              VARCHAR2(255 CHAR) NOT NULL,
  password_hash      VARCHAR2(255 CHAR) NOT NULL,
  display_name       VARCHAR2(100 CHAR) NOT NULL,
  bio                VARCHAR2(1000 CHAR),
  avatar_url         VARCHAR2(500 CHAR),
  status             VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  reputation_score   NUMBER(10,0) DEFAULT 0 NOT NULL,
  last_login_at      TIMESTAMP,
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  deleted_at         TIMESTAMP,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DELETED'))
);

CREATE TABLE roles (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  role_code          VARCHAR2(50 CHAR) NOT NULL,
  role_name          VARCHAR2(100 CHAR) NOT NULL,
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_roles PRIMARY KEY (id),
  CONSTRAINT uq_roles_role_code UNIQUE (role_code)
);

CREATE TABLE user_roles (
  user_id            NUMBER NOT NULL,
  role_id            NUMBER NOT NULL,
  granted_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-------------------------------------------------------------------------------
-- CONTENT DOMAIN
-------------------------------------------------------------------------------
CREATE TABLE topics (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  code               VARCHAR2(50 CHAR) NOT NULL,
  name               VARCHAR2(100 CHAR) NOT NULL,
  description        VARCHAR2(500 CHAR),
  sort_order         NUMBER(6,0) DEFAULT 100 NOT NULL,
  is_active          NUMBER(1,0) DEFAULT 1 NOT NULL,
  created_by         NUMBER,
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_topics PRIMARY KEY (id),
  CONSTRAINT uq_topics_code UNIQUE (code),
  CONSTRAINT ck_topics_is_active CHECK (is_active IN (0, 1)),
  CONSTRAINT fk_topics_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE posts (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  topic_id           NUMBER NOT NULL,
  author_id          NUMBER NOT NULL,
  title              VARCHAR2(200 CHAR) NOT NULL,
  body               CLOB NOT NULL,
  post_type          VARCHAR2(20 CHAR) DEFAULT 'ARTICLE' NOT NULL,
  visibility         VARCHAR2(20 CHAR) DEFAULT 'PUBLIC' NOT NULL,
  status             VARCHAR2(20 CHAR) DEFAULT 'PUBLISHED' NOT NULL,
  view_count         NUMBER(12,0) DEFAULT 0 NOT NULL,
  like_count         NUMBER(12,0) DEFAULT 0 NOT NULL,
  comment_count      NUMBER(12,0) DEFAULT 0 NOT NULL,
  accepted_comment_id NUMBER,
  published_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  deleted_at         TIMESTAMP,
  CONSTRAINT pk_posts PRIMARY KEY (id),
  CONSTRAINT fk_posts_topic FOREIGN KEY (topic_id) REFERENCES topics(id),
  CONSTRAINT fk_posts_author FOREIGN KEY (author_id) REFERENCES users(id),
  CONSTRAINT ck_posts_post_type CHECK (post_type IN ('ARTICLE', 'QUESTION')),
  CONSTRAINT ck_posts_visibility CHECK (visibility IN ('PUBLIC', 'MEMBERS_ONLY', 'PRIVATE')),
  CONSTRAINT ck_posts_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE TABLE post_versions (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  post_id            NUMBER NOT NULL,
  version_no         NUMBER(6,0) NOT NULL,
  title              VARCHAR2(200 CHAR) NOT NULL,
  body               CLOB NOT NULL,
  edited_by          NUMBER NOT NULL,
  edited_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  edit_reason        VARCHAR2(500 CHAR),
  CONSTRAINT pk_post_versions PRIMARY KEY (id),
  CONSTRAINT uq_post_versions_post_version UNIQUE (post_id, version_no),
  CONSTRAINT fk_post_versions_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_post_versions_edited_by FOREIGN KEY (edited_by) REFERENCES users(id)
);

CREATE TABLE comments (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  post_id            NUMBER NOT NULL,
  author_id          NUMBER NOT NULL,
  parent_comment_id  NUMBER,
  content            VARCHAR2(4000 CHAR) NOT NULL,
  is_deleted         NUMBER(1,0) DEFAULT 0 NOT NULL,
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_comments PRIMARY KEY (id),
  CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users(id),
  CONSTRAINT fk_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES comments(id) ON DELETE CASCADE,
  CONSTRAINT ck_comments_is_deleted CHECK (is_deleted IN (0, 1))
);

ALTER TABLE posts
  ADD CONSTRAINT fk_posts_accepted_comment
  FOREIGN KEY (accepted_comment_id) REFERENCES comments(id);

CREATE TABLE tags (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name               VARCHAR2(50 CHAR) NOT NULL,
  normalized_name    VARCHAR2(50 CHAR) NOT NULL,
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_tags PRIMARY KEY (id),
  CONSTRAINT uq_tags_normalized_name UNIQUE (normalized_name)
);

CREATE TABLE post_tags (
  post_id            NUMBER NOT NULL,
  tag_id             NUMBER NOT NULL,
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_post_tags PRIMARY KEY (post_id, tag_id),
  CONSTRAINT fk_post_tags_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_post_tags_tag FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

CREATE TABLE attachments (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  post_id            NUMBER NOT NULL,
  uploaded_by        NUMBER NOT NULL,
  file_name          VARCHAR2(255 CHAR) NOT NULL,
  stored_name        VARCHAR2(255 CHAR) NOT NULL,
  file_url           VARCHAR2(1000 CHAR) NOT NULL,
  mime_type          VARCHAR2(150 CHAR),
  file_size_bytes    NUMBER(12,0) NOT NULL,
  checksum_sha256    VARCHAR2(64 CHAR),
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_attachments PRIMARY KEY (id),
  CONSTRAINT fk_attachments_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_attachments_user FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

-------------------------------------------------------------------------------
-- REACTIONS & PERSONALIZATION
-------------------------------------------------------------------------------
CREATE TABLE post_reactions (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  post_id            NUMBER NOT NULL,
  user_id            NUMBER NOT NULL,
  reaction_type      VARCHAR2(20 CHAR) DEFAULT 'LIKE' NOT NULL,
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_post_reactions PRIMARY KEY (id),
  CONSTRAINT uq_post_reactions_user UNIQUE (post_id, user_id, reaction_type),
  CONSTRAINT fk_post_reactions_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_post_reactions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT ck_post_reactions_type CHECK (reaction_type IN ('LIKE', 'CLAP', 'INSIGHTFUL'))
);

CREATE TABLE bookmarks (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  post_id            NUMBER NOT NULL,
  user_id            NUMBER NOT NULL,
  memo               VARCHAR2(500 CHAR),
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_bookmarks PRIMARY KEY (id),
  CONSTRAINT uq_bookmarks_post_user UNIQUE (post_id, user_id),
  CONSTRAINT fk_bookmarks_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_bookmarks_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-------------------------------------------------------------------------------
-- AUDIT / MODERATION
-------------------------------------------------------------------------------
CREATE TABLE moderation_logs (
  id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  target_type        VARCHAR2(30 CHAR) NOT NULL,
  target_id          NUMBER NOT NULL,
  action             VARCHAR2(30 CHAR) NOT NULL,
  reason             VARCHAR2(1000 CHAR),
  acted_by           NUMBER NOT NULL,
  acted_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_moderation_logs PRIMARY KEY (id),
  CONSTRAINT fk_moderation_logs_actor FOREIGN KEY (acted_by) REFERENCES users(id),
  CONSTRAINT ck_moderation_logs_target CHECK (target_type IN ('POST', 'COMMENT', 'USER')),
  CONSTRAINT ck_moderation_logs_action CHECK (action IN ('HIDE', 'DELETE', 'RESTORE', 'SUSPEND', 'UNSUSPEND'))
);

-------------------------------------------------------------------------------
-- INDEXES
-------------------------------------------------------------------------------
CREATE INDEX idx_users_status_created_at ON users(status, created_at DESC);
CREATE INDEX idx_topics_active_sort ON topics(is_active, sort_order);
CREATE INDEX idx_posts_topic_published ON posts(topic_id, published_at DESC);
CREATE INDEX idx_posts_author_created ON posts(author_id, created_at DESC);
CREATE INDEX idx_posts_status_visibility ON posts(status, visibility, published_at DESC);
CREATE INDEX idx_comments_post_created ON comments(post_id, created_at);
CREATE INDEX idx_comments_parent ON comments(parent_comment_id);
CREATE INDEX idx_post_reactions_post_type ON post_reactions(post_id, reaction_type);
CREATE INDEX idx_bookmarks_user_created ON bookmarks(user_id, created_at DESC);
CREATE INDEX idx_attachments_post ON attachments(post_id);
CREATE INDEX idx_moderation_target ON moderation_logs(target_type, target_id, acted_at DESC);

-------------------------------------------------------------------------------
-- SEED DATA
-------------------------------------------------------------------------------
INSERT INTO roles (role_code, role_name) VALUES ('ADMIN', '관리자');
INSERT INTO roles (role_code, role_name) VALUES ('MEMBER', '일반회원');

INSERT INTO users (email, password_hash, display_name, status)
VALUES (
  'admin@example.com',
  '$2y$10$qf9qAKr84rKQ7i3F20z6MutKD4x5x0Fgx4nR2DP6PAHyBs64K6l1m',
  '관리자',
  'ACTIVE'
);

INSERT INTO topics (code, name, description, sort_order, is_active, created_by)
VALUES ('ai-practical', 'AI 실무활용', 'AI를 실무에 적용하는 노하우를 공유하는 공간', 1, 1, 1);

COMMIT;
